### ISSUE TITLE
Issue when using sub application on IIS

### ISSUE THREAD

**Issue by chuannt11673** [topnguyen/Elect#10]
Hi, I'm currently hosting my Net core web app into IIS. However, I create a sub application under default website and provide it an Alias name instead of creating a new one. 
Then it got this issue because the Url is incorrect.
I'm using Elect.Web.Swagger v3.1.5
![image](https://user-images.githubusercontent.com/37902578/89781133-f5685e80-db3c-11ea-97ca-cdcc8b891a8c.png)
The request url should start with http://localhost/Api/ (Api here is the alias that I named it)

**Comment by topnguyen** [comment]
Hi @chuannt11673 

You can config the postfix for the root app endpoint via the model, see more [here](https://github.com/topnguyen/Elect/blob/master/src/Web/Elect.Web.Swagger/Models/ElectSwaggerOptions.cs#L39)

And it will apply to the swagger UI configuration [here](https://github.com/topnguyen/Elect/blob/master/src/Web/Elect.Web.Swagger/IApplicationBuilderExtensions.cs#L86)

You can check more how to config the swagger in asp net core via [this tutorial](https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-3.1&tabs=visual-studio)

Then feel free to adjust the configuration of swagger accordingly your app.

**Comment by topnguyen** [comment]
Hi @chuannt11673 

Please check variable `window.swaggerUi.url` in [this file](https://github.com/topnguyen/Elect/blob/master/src/Web/Elect.Web.Swagger/Elect_Swagger/index.html#L56)

You can find it by folder named `Elect_Swagger` in the deployment or bin directory. 

If it points to the `localhost` instead of `localhost/<your subfolder>`, then please correct it and put it to your deploy package.

**Comment by topnguyen** [comment]
Close this issue due to no update for a long time.
