### ISSUE TITLE
Elect.Notification.OneSignal CancelAsync AppId not found

### ISSUE THREAD

**Issue by andrewmorris-dev** [topnguyen/Elect#4]
Hi @topnguyen 

I was using your library to communicate sending push notifications to OnSignal, which I am able to do with the CreateAsync method. However, when I try to cancel a scheduled notification in OneSignal I get the following error message:

`"app_id not found. You may be missing a Content-Type: application/json header."`

I have tried both overloads of the method and both return me the same error above.

`await _oneSignal.CancelAsync(dbObj.OneSignalId, _appSettings.OneSignalSettings.AppId);`

`await _oneSignal.CancelAsync(dbObj.OneSignalId, _appSettings.OneSignalSettings.AppId, _appSettings.OneSignalSettings.ApiKey);`

**Comment by topnguyen** [comment]
Hi @andrewmorris-dev 

So sorry for my late response.

I have updated the `CancelAsync` and put the header "Content-Type: application/json; charset=utf-8"

I refer to use the code below if you not config the Apps in `services.AddElectNotificationOneSignal()`
```c#
await _oneSignal.CancelAsync(dbObj.OneSignalId, _appSettings.OneSignalSettings.AppId, _appSettings.OneSignalSettings.ApiKey);
```

Please check the new version of Nuget via https://www.nuget.org/packages/Elect.Notification.OneSignal/2.7.1
OR
http://nuget.topnguyen.com/packages/Elect.Notification.OneSignal

**Comment by andrewmorris-dev** [comment]
Hi @topnguyen 

Thanks for the update, however, after updating my project with the latest package version through nuget, I still get the same error:

`"app_id not found. You may be missing a Content-Type: application/json header."`

I did try both overloads again, but only after the trying your suggested option first after it returned the error. 

This is the configuration I have setup in Startup.cs

```
services.AddElectOneSignal(options =>
{
                options.AuthKey = appSettings.OneSignalSettings.AuthKey;
                options.Apps = new List<ElectOneSignalAppOption>
                {
                    new ElectOneSignalAppOption
                    {
                        ApiKey = appSettings.OneSignalSettings.ApiKey,
                        AppId = appSettings.OneSignalSettings.AppId,
                        AppName = appSettings.OneSignalSettings.AppName
                    }
                };
});
```

**Comment by topnguyen** [comment]
Let I do more testing then update you soon

**Comment by andrewmorris-dev** [comment]
Ok, thanks @topnguyen 

I did come across something similar, albeit for an Android SDK, where the underlining issue was due to a  versioning issue of OneSignal. Hope it helps:

https://github.com/OneSignal/OneSignal-Android-SDK/issues/519

**Comment by topnguyen** [comment]
Hi @andrewmorris-dev,

I found the root cause and fixed it.

Please check version 2.7.2
https://www.nuget.org/packages/Elect.Notification.OneSignal/2.7.2
OR
http://nuget.topnguyen.com/packages/Elect.Notification.OneSignal

Note:
- You only can cancel the "scheduled notification", [read more](https://documentation.onesignal.com/reference#section-delivery).
- In your code
    + The first parameter is wrong, it is "Notification Id" instead of "App Id".

```c#

// CHANGE FROM

await _oneSignal.CancelAsync(dbObj.OneSignalId, _appSettings.OneSignalSettings.AppId, _appSettings.OneSignalSettings.ApiKey);

// TO

await _oneSignal.CancelAsync(*Notification Id*, _appSettings.OneSignalSettings.AppId, _appSettings.OneSignalSettings.ApiKey);
```

Please feel free to contact me again if anything not clear.

Happy Coding!

**Comment by andrewmorris-dev** [comment]
Hi @topnguyen 

Wonderful, thanks for fixing the issue, I'm able to cancel the notification I had scheduled now. 

Just out of interest, what was the root cause of the issue?

Thanks again

**Comment by topnguyen** [comment]
Hi @andrewmorris-dev 

There are 2 issues

Firstly, you have put "App Id" instead of "Notification id", so it throws the error you faced.

Secondly, 
I have tried to put "Notification Id" and get `400 Bad Request` error.
Due to the Endpoint is not correct, I have adjusted the URL pattern from `Route` to `Query String` for `app_id` param, please see more detail in [this commit](https://github.com/topnguyen/Elect/commit/966c80c8194dccdf1987fc740ac76c6a4358a004#diff-b5b90fd1178d20dbe982986c25c07a72)

You can check my Unit Testing [here](https://github.com/topnguyen/Elect/blob/master/test/Notification/Elect.Test.Notification.Onesignal/OnesignalUnitTest.cs#L93).

**Comment by andrewmorris-dev** [comment]
Thanks @topnguyen ,

My dbObj is just a database table called Notifications, where OneSignalId is actually the NotificationId from OneSignal, I should probably rename the OneSignalId field to OneSignalNotificationId instead as I can see the confusion.

Thanks for providing the commit details too, I see that by using the SetQueryParam, Flurl will auto encode that as well, pretty cool. 

Thanks again @topnguyen , you've created an awesome library.

**Comment by topnguyen** [comment]
Thank @andrewmorris-dev, you give me very useful information to improve the library.
